version: "2.10"
services:
  server:
    build: ./node
    container_name: server_c
    environment:
      - DATABASE_URI=mongodb://mongodb:27017/authnauth
      - ACCESS_TOKEN_SECRET=authnauth
      - REFRESH_TOKEN_SECRET=authnauth
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  client:
    build: ./demo-app
    container_name: client_c
    ports:
      - "3000:3000"
    stdin_open: true
  mongodb:
    container_name: mongo_c
    image: mongo
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
