apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: client
  template:
    metadata:
      labels:
        component: client
    spec:
      containers:
        - name: client
          image: roopeshsn/authnauth-react
          ports:
            - containerPort: 3000
          env:
            - name: "BASE_URL"
              value: "http://server-service:5000"

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: NodePort
  selector:
    component: client
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31350
